name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        project_id: sylvan-altar-424311-a8  # Replace with your Google Cloud project ID

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Install app-engine-go component
      run: |
        sudo apt-get update
        sudo apt-get install google-cloud-sdk-app-engine-go

    - name: Install dependencies
      run: go mod download

    - name: Deploy to App Engine
      run: gcloud app deploy app.yaml --quiet
