name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK and app-engine-go
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        version: '330.0.0'  # Specify the Google Cloud SDK version
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        additional_components: app-engine-go

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Install dependencies
      run: go mod download

    - name: Deploy to App Engine
      run: gcloud app deploy app.yaml --quiet
