name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        project_id: sylvan-altar-424311-a8  # Replace with your Google Cloud project ID

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Install gcloud CLI
      run: |
        curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-369.0.0-linux-x86_64.tar.gz
        tar -xzf google-cloud-sdk-369.0.0-linux-x86_64.tar.gz
        ./google-cloud-sdk/install.sh --quiet

    - name: Verify gcloud installation
      run: gcloud version

    - name: Install app-engine-go component (if needed)
      run: gcloud components install app-engine-go --quiet || true

    - name: Install dependencies
      run: go mod download

    - name: Deploy to App Engine
      run: gcloud app deploy app.yaml --quiet
